{% set name = "staircase" %}
{% set version = "2.7.0" %}
{% set sha = "3df0f3b012c041375303915ff89fb444d2e1db369e4e0038e51e1188eeecbf9a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - poetry
  run:
    - matplotlib-base >3.0.0,<4
    - numpy >=1.16.0,<3
    - pandas >=1,<3
    - python >=3.8,<4
    - pytz

test:
  imports:
    - staircase

about:
  home: https://staircase.dev
  summary: A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  license: MIT
  license_file: LICENSE
  description: |
    A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  doc_url: https://staircase.dev
  doc_source_url: https://github.com/staircase-dev/staircase/blob/master/docs/index.rst
  dev_url: https://github.com/staircase-dev/staircase


extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
