{% set name = "staircase" %}
{% set version = "2.0.4" %}
{% set sha = "25e019e3d3d930153bd2c5381029198e865db0b0732fdda6f85550930ffee14c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - matplotlib-base >3.0.0,<4
    - numpy >=1.16.0,<2
    - pandas >=0.24,<3
    - python >=3.6,<4
    - pytz

test:
  imports:
    - staircase

about:
  home: https://staircase.dev
  summary: A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  license: MIT
  license_file: LICENSE
  description: |
    A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  doc_url: https://staircase.dev
  doc_source_url: https://github.com/staircase-dev/staircase/blob/master/docs/index.rst
  dev_url: https://github.com/staircase-dev/staircase


extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
