{% set name = "staircase" %}
{% set version = "1.6.0" %}
{% set sha = "65652ee6f934c93a65f7f9b4d451bda777bf183f537047f260b6cc067346b025" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >3.0.0,<4
    - numpy >=1.16.0,<2
    - pandas >=0.24,<2
    - python >=3.6,<4
    - sortedcontainers >=2,<3
    - pytz

test:
  imports:
    - staircase
    - staircase.docstrings
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pytest tests
    - python -m pip check

about:
  home: https://github.com/venaturum/staircase
  summary: Modelling of quantitative state changes as step functions
  license: MIT
  license_file: LICENSE
  summary: An open source library for (mathematical) step functions
  description: |
    Staircase facilitates the modelling, manipulation 
    and analysis of data with (mathematical) step functions
  doc_url: https://railing.readthedocs.io
  doc_source_url: https://github.com/venaturum/staircase/blob/master/docs/index.rst
  dev_url: https://github.com/venaturum/staircase


extra:
  recipe-maintainers:
    - venaturum
