{% set name = "staircase" %}
{% set version = "2.3.0" %}
{% set sha = "3f6ca26bf9cc0e6c6bb1fb08071457d5c10522cc99e3031a961371f29b6a162f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
    - poetry
  run:
    - matplotlib-base >3.0.0,<4
    - numpy >=1.16.0,<2
    - pandas >=1,<2
    - python >=3.6.1,<4
    - pytz

test:
  imports:
    - staircase

about:
  home: https://staircase.dev
  summary: A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  license: MIT
  license_file: LICENSE
  description: |
    A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  doc_url: https://staircase.dev
  doc_source_url: https://github.com/staircase-dev/staircase/blob/master/docs/index.rst
  dev_url: https://github.com/staircase-dev/staircase


extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
